<?php
/**
* @file
* A description of what your module does.
*/

/**
 * @return array
 * В добавлении нового поля должно появиться наше новое поле. Вначале определим тип поля. Поместим в файл test_fuields.module следующую функцию.
 * Теперь можно будет добавить к материалу поле типа «Выбор пола».  Значение элемента default_widget , равное textf_widget==alfaq_field_widget говорит о том,
 * что тип виджета будет называться textf. С ним мы будем работать чуть позже. Этот виджет будет отвечать за то, какого типа будет поле в форме добавления ноды.
 */

function field_api_field_info() {
    return array(
        'alfaq_field' => array(
            'label' => t('Select sex'),
            'description' => t('Description field'),
            'default_widget' => 'alfaq_field_widget',
            'default_formatter' => 'alfaq_field_formatter', // name line 47, по умолчанию будет выбран формат вывода label
        ),
    );
}

/**
 * @return array
 * Теперь нужно дать описание полю, чтобы пользователь понимал поле какого типа он добавляет к материалу – поле ввода, текстовую область, выпадающий список и т.д.
 * Можно вписать сюда всё что угодно.
 */

function field_api_field_widget_info() {
    return array(
        'alfaq_field' => array(
            'label' => t('Selector'),
            'field types' => array('alfaq_field'),
        ),
    );
}

/**
 * Также для поля нужен формат вывода.
 * Для этого используем hook_field_formatter_info. Пусть Drupal будет выводить М/Ж или  Мужчина/Женщина. Напишем следующую функцию.
 */

function field_api_field_formatter_info() {
    return array(
        'alfaq_field_formatter' => array(
            'label' => t('label'),
            'field types' => array('alfaq_field'),
        ),
        'alfaq_field_formatter_2' => array(
            'label' => t('text'),
            'field types' => array('alfaq_field'),
        ),
    );
}

/**
 * Далее определимся – как будет выглядеть элемент формы на странице !!!добавления ноды!!!
 * Пусть это будет два радиобутона. Для этого используем hook_field_widget_form и вспомним о создании форм в Drupal. Напишем следующую функцию.
 */

function field_api_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
    switch ($instance['widget']['type']) {
        case 'alfaq_field':
            $element['alfaq_field'] = array(
                '#type' => 'radios',
                '#options' => array(1 => t('M'), 2 => t('W')),
                '#title' => $element['#title'],
                '#description' => $element['#description'],
                '#default_value' => isset($items[0]['alfaq_field']) ? $items[0]['alfaq_field'] : 1,
                '#required' => $element['#required'],
                '#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
                '#delta' => $delta,
            );
            break;
    }
    return $element;
}